POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "fullName": "dare loko",
    "email": "dare@gmail.com",
    "mobileNumber": "081278453328",
    "address": "awojobi, loco harcourt",
    "gender": "female",
    "password": "password91"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "ayoolaanibabs@gmail.com",
    "password": "password"
}

###
POST http://localhost:3000/suggest
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6IkF5b29sYSBBbmliYWJhIiwiaWF0IjoxNjA2NTE4Mzk3LCJleHAiOjE2MDY1MjE5OTd9.t98rNoeslfTFaLIYoNbg_WMrDYhoa8TJyTKgdhi10EQ
Content-Type: application/json

{
    "itemName": "televison809",
    "itemDescription": "42 inches television set",
    "itemCategory":"electronics",
    "reason": "For watching football"
}

###
GET http://localhost:3000/suggested
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6IkF5b29sYSBBbmliYWJhIiwiaWF0IjoxNjA2NTE4Mzk3LCJleHAiOjE2MDY1MjE5OTd9.t98rNoeslfTFaLIYoNbg_WMrDYhoa8TJyTKgdhi10EQ

###
GET http://localhost:3000/suggested/electronics
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6IkF5b29sYSBBbmliYWJhIiwiaWF0IjoxNjA2NTE4Mzk3LCJleHAiOjE2MDY1MjE5OTd9.t98rNoeslfTFaLIYoNbg_WMrDYhoa8TJyTKgdhi10EQ